version: "3.0"
services:
  postgres:
    image:  postgres:latest
    restart: unless-stopped
    container_name: psg
    env_file:
      - ".env"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - TZ=${TZ}
    volumes:
      - "./docker/postgres:/var/lib/postgresql/data:Z"

  redis:
    image: redis:latest
    container_name: redis_v2

  site:
    container_name: site_v2
    build: .
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    env_file:
      - ".env"
    environment:
      - TZ=${TZ}
      - C_FORCE_ROOT=1
    ports:
      - "127.0.0.1:8008:8000"
    depends_on:
      - postgres
      - redis

    tty: true
    volumes:
      - "./:/srv/site:Z"
